### ISSUE TITLE
Source code of Fragment for NekoBox

### ISSUE THREAD

**Issue by Graveyard9988** [Mahdi-zarei/nekoray#1]
Source code of tls fragment for NekoBox:

https://github.com/maskedeken/sing-box/commit/a42d2e6fd16d9bd359c828e9d527430e05d1ed4b

https://github.com/maskedeken/NekoBoxForAndroid/commit/b915370224737a8e0db770adbc6146415f5cbc64

Please add them to your fork ☝️

Regards.

**Comment by Mahdi-zarei** [comment]
Regarding mux, both Husi and Nekoray do support mux, Xray's and sing-box's mux implementations are not compatible so if mux is to be employed both server and the client have to use the same core. About fragment, it's a feature of the core and not the GUI, the fork of sing-box you provided appears to be poorly maintained and is around a year behind the upstream sing-box project. Also the main idea of fragmentation is practically a very poor idea since fragmentation of clientHello Packet is a very rare event and GFW could simply block any connection that has its clientHello packet fragmented, so this feature is not working because it is a brilliant idea, but because they have not decided to block it yet. I can suggest using hiddify's client which uses a fork of sing-box which supports fragment and is available for both android and windows (also apple platform).
