### ISSUE TITLE
BUG: the correct configurations

### ISSUE THREAD

**Issue by papan2084** [Mahdi-zarei/nekoray#108]
Hello, I can't find, the correct configs, without a download test on 4.1.2
I use free configurations for a variety of reasons, and because they are so many and often fake and do not work properly; The download test is a big help to find those who work.
Also, I would be grateful if you could guide me to find a dns that works better with my service line

**Comment by Mahdi-zarei** [comment]
Download tests are not really useful since they cannot be used on multiple profiles at once, and for small number of profiles it's better to use proper speedtesting tools like Speedtest.net manually.
I don't understand what you mean by finding a dns server that works better, but unless there are some privacy concerns, the lesser the ping to the dns server the better, and use dns over TLS if there are privacy concerns.
