### ISSUE TITLE
[FR] Option to edit active rules section

### ISSUE THREAD

**Issue by papampi** [Mahdi-zarei/nekoray#68]
## Description suggestions
Active rules in left section is inactive, we can't either scroll or edit. 
If possible and no headache please add a checkmark option to activate it, so those who want can manually edit or scroll and check its content. 

![image](https://github.com/Mahdi-zarei/nekoray/assets/1108483/a4fd3331-d70c-4f09-a772-5e244053b29c)

![Screenshot from 2024-06-30 12-47-44](https://github.com/Mahdi-zarei/nekoray/assets/1108483/9c4c4df0-6f03-4a66-a713-d0881499b2bf)

**Comment by Mahdi-zarei** [comment]
Editing them is not going to work well given that they have to be in the Json format and errors cannot fixed, but viewing them should be fixed. Also Import json can be used to manually import the json array. Also I think we need an export json so that we can export the array and then change it and import it again, in case someone wants to use a complex routing rule.

**Comment by Mahdi-zarei** [comment]
توی نسخه جدید رفع شده مشکل اسکرول نشدن، تست کنید.
