### ISSUE TITLE
[FR]: Periodically alpha/beta updates 

### ISSUE THREAD

**Issue by papampi** [Mahdi-zarei/nekoray#97]
Thanks for your awesome continuous work on your fork.

Since we can see lots of commits are adding to your fork if possible please add some periodically alpha/beta updates so we users can benefit from new changes, get  use to them and test them for stable releases.

**Comment by Sue1133** [comment]
You can download them from the Actions tab.

**Comment by Mahdi-zarei** [comment]
You are right, I was also thinking about releasing betas to achieve both quicker releases and more stable main releases.


> You can download them from the Actions tab.

I strongly suggest that you don't do it. Those builds are not even guaranteed to be runnable and use them to test compatibility since my own environment has many libraries and tools that may be used by the App.
